const API='https://asendex-testnet-beta.vercel.app/api/read';
const EXPLORER='https://explorer.asentum.com';
const NATIVE={symbol:'ASE',name:'Asentum',address:'0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',decimals:18,native:true};
const TREASURY='ase16qnk8kgjajray9dltuauf8a7jzjtt0ul5rwqxm';
const FEE_BPS=10n,FEE_DENOM=10000n,GAS_RESERVE=100000000000000n;
const FALLBACK=[
 {symbol:'AURA',address:'0xc24044dccea3ba8b362e1c85fa16ddc658022269',decimals:18,poolId:'1'},
 {symbol:'NOVA',address:'0xbea7c12cba13eddd8e8ad77ff8f62fcf27736d20',decimals:18,poolId:'2'},
 {symbol:'PULSE',address:'0x50cb8d861050ad0052959e0f942c5347842346f1',decimals:18,poolId:'3'},
 {symbol:'ZEPH',address:'0xde4480220ba5793bff42fd9162954fa3fdb1acd3',decimals:18,poolId:'4'},
 {symbol:'ORB',address:'0xe91421ecfe12f18814dc8c0635267fb2dc86ac6f',decimals:18,poolId:'5'}
];
const FALLBACK_AMM='0x63f640a9b98b6f28e06cb5cc0fce5d72b6c0eabd';
let seq=1,pending={};
let address='',pairs=[],tokens=[NATIVE],balances=new Map(),quoteOut=0n,minOut=0n,quoteAt=0,priceImpact=null,networkHealthy=false;
let bio={available:false,enabled:false};
const $=id=>document.getElementById(id);
const short=a=>a&&a.length>16?`${a.slice(0,7)}…${a.slice(-5)}`:(a||'—');
const wait=ms=>new Promise(r=>setTimeout(r,ms));

function bridge(method,params={}){return new Promise((resolve,reject)=>{const id=String(seq++);pending[id]={resolve,reject};AppBridge.request(id,JSON.stringify({method,params}));});}
window.__appResolve=function(id,ok,json){const p=pending[String(id)];if(!p)return;delete pending[String(id)];let d={};try{d=json?JSON.parse(json):{};}catch{d={message:json}};ok?p.resolve(d):p.reject(new Error(d.message||'Falha na wallet'));};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function cleanHex(v){return String(v||'').trim().replace(/\s+/g,'').replace(/^0x/i,'');}
function validContract(v){return /^0x[0-9a-fA-F]{40}$/.test(String(v||'').trim());}
function parseUnits(v,d=18){const s=String(v||'').trim();if(!/^\d*(\.\d*)?$/.test(s)||!s)return 0n;let[a,b='']=s.split('.');b=(b+'0'.repeat(d)).slice(0,d);return BigInt(a||0)*10n**BigInt(d)+BigInt(b||0);}
function formatUnits(v,d=18,p=8){v=BigInt(v||0);const z=10n**BigInt(d),a=v/z,b=(v%z).toString().padStart(d,'0').slice(0,p).replace(/0+$/,'');return b?`${a}.${b}`:String(a);}
function fmt(n,p=4){return Number(n||0).toLocaleString(undefined,{maximumFractionDigits:p});}
function toast(msg){const e=$('toast');if(!e)return;e.textContent=msg;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),2200);}
function setBusy(el,busy,label){if(!el)return;if(busy){el.dataset.label=el.textContent;el.disabled=true;if(label)el.textContent=label;}else{el.disabled=false;if(el.dataset.label)el.textContent=el.dataset.label;}}

async function api(mode,payload={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,...payload}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'Falha de leitura ASENDEX');return j;}
async function view(contract,method,args=[]){return (await bridge('viewContract',{to:contract,method,args})).result;}
async function receipt(hash){for(let i=0;i<60;i++){try{const r=(await api('receipt',{txHash:hash})).receipt;if(r?.blockNumber)return r;}catch{}await wait(1500)}return null;}
function rcptOk(r){if(r?.success===true)return true;if(r?.success===false)return false;const s=String(r?.status??'').toLowerCase();return s==='0x1'||s==='1'||s==='true';}

function customTokens(){try{return JSON.parse(localStorage.getItem('asendex.mobile.customTokens')||'[]')}catch{return[]}}
function saveCustom(list){localStorage.setItem('asendex.mobile.customTokens',JSON.stringify(list.slice(0,40)));}
function tokenByAddress(a){return tokens.find(t=>t.address.toLowerCase()===String(a||'').toLowerCase());}
function findPair(a,b){if(!a||!b||a.address===b.address)return null;const x=a.native?b:(b.native?a:null);if(!x)return null;return pairs.find(p=>String(p.token0).toLowerCase()===x.address.toLowerCase()||String(p.token1).toLowerCase()===x.address.toLowerCase())||null;}

async function loadMarkets(){
 let live=[];
 try{const j=await api('pairs');live=j.data?.pairs||[];}catch{}
 if(!live.length){live=FALLBACK.map(t=>({poolId:t.poolId,amm:FALLBACK_AMM,base:t.symbol,quote:'ASE',token0:t.address,token1:NATIVE.address,feeBps:30,tvlQuote:0,price:0}));}
 pairs=live;
 const map=new Map();
 for(const p of live){for(const [addr,sym] of [[p.token0,p.base],[p.token1,p.quote]]){if(String(addr).toLowerCase()===NATIVE.address)continue;if(!map.has(String(addr).toLowerCase()))map.set(String(addr).toLowerCase(),{symbol:sym||'TOKEN',name:sym||'Token',address:addr,decimals:18,native:false,poolId:String(p.poolId)});}}
 for(const t of FALLBACK){if(!map.has(t.address.toLowerCase()))map.set(t.address.toLowerCase(),{...t,name:t.symbol,native:false});}
 for(const t of customTokens()){if(validContract(t.address)&&!map.has(t.address.toLowerCase()))map.set(t.address.toLowerCase(),{...t,native:false,custom:true});}
 tokens=[NATIVE,...map.values()];
 await Promise.all(tokens.slice(1).map(async t=>{try{const d=Number(await view(t.address,'decimals',[]));if(Number.isFinite(d)&&d>=0&&d<=36)t.decimals=d;}catch{}try{const s=String(await view(t.address,'symbol',[])||'').trim();if(s)t.symbol=s;}catch{}try{const n=String(await view(t.address,'name',[])||'').trim();if(n)t.name=n;}catch{}}));
 renderTokenSelectors();renderAssets();
}
async function balanceRaw(t){if(!address)return 0n;if(t.native)return BigInt((await api('balance',{address})).balance||0);try{return BigInt(await view(t.address,'balanceOf',[address])||0)}catch{return 0n}}
async function refreshBalances(){if(!address)return;await Promise.all(tokens.map(async t=>{try{balances.set(t.address.toLowerCase(),await balanceRaw(t));}catch{balances.set(t.address.toLowerCase(),0n)}}));renderAssets();updateSwapBalances();const ase=balances.get(NATIVE.address)||0n;$('balance').textContent=`${formatUnits(ase,18,6)} ASE`;$('assetBalance').textContent=formatUnits(ase,18,6);}

function renderAssets(){const box=$('assetList');if(!box)return;box.innerHTML='';for(const t of tokens){const bal=balances.get(t.address.toLowerCase());const p=t.native?null:findPair(NATIVE,t);const row=document.createElement('div');row.className='asset';row.innerHTML=`<div class="coin">${esc((t.symbol||'?').slice(0,2))}</div><div class="grow"><div class="name">${esc(t.symbol)} <span class="tinyTag">${t.native?'NATIVE':p?'POOL':'TOKEN'}</span></div><div class="meta mono">${t.native?'Asentum native asset':esc(short(t.address))}</div></div><div class="right"><div class="name">${bal==null?'—':esc(formatUnits(bal,t.decimals,6))}</div><div class="meta">${esc(t.symbol)}</div></div>`;row.onclick=()=>{if(!t.native){showTab('swap');$('fromToken').value=NATIVE.address;$('toToken').value=t.address;swapChanged('to');}};box.appendChild(row);}}
function renderTokenSelectors(){for(const id of ['fromToken','toToken']){const el=$(id);if(!el)continue;const old=el.value;el.innerHTML='';for(const t of tokens){const o=document.createElement('option');o.value=t.address;o.textContent=t.symbol;el.appendChild(o);}if(tokens.some(t=>t.address===old))el.value=old;}if(!$('fromToken').value)$('fromToken').value=NATIVE.address;if(!$('toToken').value||$('toToken').value===NATIVE.address)$('toToken').value=tokens.find(t=>!t.native)?.address||NATIVE.address;updateSwapBalances();}
function updateSwapBalances(){const a=tokenByAddress($('fromToken')?.value),b=tokenByAddress($('toToken')?.value);if(a)$('fromBalance').textContent=`Saldo ${formatUnits(balances.get(a.address.toLowerCase())||0n,a.decimals,6)} ${a.symbol}`;if(b)$('toBalance').textContent=`Saldo ${formatUnits(balances.get(b.address.toLowerCase())||0n,b.decimals,6)} ${b.symbol}`;}

async function networkCheck(){try{const j=await api('network');networkHealthy=j.healthy!==false&&j.stalled!==true&&j.rpcMismatch!==true;const e=$('networkBadge');if(e){e.textContent=networkHealthy?'REDE OK':j.stalled?'REDE PARADA':'REDE EM ALERTA';e.className='statusPill '+(networkHealthy?'ok':'bad');}return j;}catch{networkHealthy=false;const e=$('networkBadge');if(e){e.textContent='SEM RPC';e.className='statusPill bad';}return null;}}
function swapChanged(src){let a=tokenByAddress($('fromToken').value),b=tokenByAddress($('toToken').value);if(!a||!b)return;if(a.address===b.address){if(src==='from')$('toToken').value=a.native?(tokens.find(t=>!t.native)?.address||NATIVE.address):NATIVE.address;else $('fromToken').value=b.native?(tokens.find(t=>!t.native)?.address||NATIVE.address):NATIVE.address;}a=tokenByAddress($('fromToken').value);b=tokenByAddress($('toToken').value);if(a&&!a.native&&b&&!b.native){if(src==='from')$('toToken').value=NATIVE.address;else $('fromToken').value=NATIVE.address;}updateSwapBalances();quoteSwap();}
async function quoteSwap(){quoteOut=0n;minOut=0n;priceImpact=null;$('swapOutput').value='';$('quoteMeta').textContent='Insira um valor para cotar';$('riskBox').className='risk';const a=tokenByAddress($('fromToken')?.value),b=tokenByAddress($('toToken')?.value),p=findPair(a,b);const v=a?parseUnits($('swapAmount').value,a.decimals):0n;const btn=$('swapButton');btn.disabled=true;if(!a||!b||!p||v<=0n)return;try{quoteOut=BigInt(await view(p.amm,'quote',[String(p.poolId),a.address,v.toString()]));const slip=BigInt($('slippage').value||'100');minOut=quoteOut*(10000n-slip)/10000n;quoteAt=Date.now();$('swapOutput').value=formatUnits(quoteOut,b.decimals,8);const fee=a.native?v*FEE_BPS/FEE_DENOM:(b.native?quoteOut*FEE_BPS/FEE_DENOM:0n);$('quoteMeta').textContent=`Mínimo ${formatUnits(minOut,b.decimals,6)} ${b.symbol} · Pool #${p.poolId} · fee pool ${(Number(p.feeBps||0)/100).toFixed(2)}% · ASENDEX ${formatUnits(fee,18,6)} ASE`;
 const probe=v/1000n;if(probe>0n){const q=BigInt(await view(p.amm,'quote',[String(p.poolId),a.address,probe.toString()]));const linear=q*v/probe;if(linear>0n&&quoteOut<=linear)priceImpact=Number((linear-quoteOut)*10000n/linear)/100;}
 const tvl=Number(p.tvlQuote||0),risk=$('riskBox');if((priceImpact??0)>=5||tvl<25){risk.className='risk high';risk.textContent=`Risco alto · impacto ${priceImpact?.toFixed(2)??'—'}% · TVL ${fmt(tvl,2)}`;}else if((priceImpact??0)>=1||tvl<100){risk.className='risk med';risk.textContent=`Atenção · impacto ${priceImpact?.toFixed(2)??'—'}% · TVL ${fmt(tvl,2)}`;}else{risk.className='risk low';risk.textContent=`Cotação estável · impacto ${priceImpact?.toFixed(2)??'0.00'}% · TVL ${fmt(tvl,2)}`;}
 const bal=balances.get(a.address.toLowerCase())||0n;const extra=a.native?(v*FEE_BPS/FEE_DENOM+GAS_RESERVE):0n;btn.disabled=!networkHealthy||v+extra>bal||(priceImpact??0)>=20;btn.textContent=v+extra>bal?`Saldo ${a.symbol} insuficiente`:`Swap ${a.symbol} → ${b.symbol}`;
 }catch(e){$('quoteMeta').textContent='Cotação indisponível: '+e.message;}}
function decodeEvent(data){try{if(!data||!/^0x[0-9a-f]*$/i.test(data))return null;const h=data.slice(2),u=Uint8Array.from([...h.matchAll(/../g)].map(x=>parseInt(x[0],16)));return JSON.parse(new TextDecoder().decode(u));}catch{return null}}
function actualOut(rcpt,t){for(const l of rcpt?.logs||[]){const j=decodeEvent(l.data);if(j?.amountOut!=null)return BigInt(j.amountOut);if(j?.value!=null&&j?.to&&String(l.address||'').toLowerCase()===t.address.toLowerCase())return BigInt(j.value)}return null;}
async function executeSwap(){const btn=$('swapButton'),a=tokenByAddress($('fromToken').value),b=tokenByAddress($('toToken').value),p=findPair(a,b),v=parseUnits($('swapAmount').value,a?.decimals||18);if(!a||!b||!p||!v)return;setBusy(btn,true,'Revisando…');$('swapStatus').textContent='';try{const n=await networkCheck();if(!n||!networkHealthy)throw new Error('Rede Asentum não está saudável. Nenhuma transação enviada.');await refreshBalances();const bal=balances.get(a.address.toLowerCase())||0n;const extra=a.native?(v*FEE_BPS/FEE_DENOM+GAS_RESERVE):0n;if(v+extra>bal)throw new Error('Saldo insuficiente para swap + taxa + gas');const fresh=BigInt(await view(p.amm,'quote',[String(p.poolId),a.address,v.toString()]));if(quoteOut>0n){const d=quoteOut>fresh?quoteOut-fresh:fresh-quoteOut;const move=Number(d*10000n/quoteOut)/100;if(move>=3){quoteOut=fresh;await quoteSwap();throw new Error(`Cotação mudou ${move.toFixed(2)}%. Revise antes de confirmar.`);}}quoteOut=fresh;minOut=fresh*(10000n-BigInt($('slippage').value||'100'))/10000n;
 if(!a.native){let allowance=0n;try{allowance=BigInt(await view(a.address,'allowance',[address,p.amm])||0)}catch{}if(allowance<v){$('swapStatus').textContent=`Aprove ${a.symbol} para a pool…`;const ap=await bridge('callContract',{to:a.address,method:'approve',args:[p.amm,v.toString()],value:'0'});const ar=await receipt(ap.txHash);if(!ar||!rcptOk(ar))throw new Error('Approve reverteu ou não confirmou');}}
 $('swapStatus').textContent='Confirme o swap…';const tx=await bridge('callContract',{to:p.amm,method:'swapExactIn',args:[String(p.poolId),a.address,v.toString(),minOut.toString()],value:a.native?v.toString():'0'});$('swapStatus').innerHTML=`Enviado ${short(tx.txHash)} · aguardando confirmação…`;const r=await receipt(tx.txHash);if(!r)throw new Error('Timeout do recibo. Não reenvie imediatamente.');if(!rcptOk(r))throw new Error('Swap REVERTED');const out=actualOut(r,b)??quoteOut;
 let fee=0n;if(a.native)fee=v*FEE_BPS/FEE_DENOM;else if(b.native)fee=out*FEE_BPS/FEE_DENOM;let feeText='';if(fee>0n){try{$('swapStatus').textContent='Swap confirmado. Confirme a taxa ASENDEX 0,10%…';const f=await bridge('sendTransfer',{to:TREASURY,amount:fee.toString(),unit:'wei'});feeText=` · fee ${short(f.txHash)}`;}catch{feeText=' · fee pendente';}}
 $('swapStatus').innerHTML=`<span class="good">CONFIRMED ✓</span> · <a href="#" onclick="openExplorer('${esc(tx.txHash)}');return false">${short(tx.txHash)}</a>${feeText}`;$('swapAmount').value='';$('swapOutput').value='';await refreshBalances();await loadActivity();toast('Swap confirmado');
 }catch(e){$('swapStatus').textContent='Swap interrompido: '+e.message;}finally{setBusy(btn,false);await quoteSwap();}}

async function searchContract(){const input=$('tokenContract'),box=$('tokenResult'),addr=input.value.trim();box.innerHTML='';if(!validContract(addr)){box.innerHTML='<div class="error">Contrato inválido. Use endereço 0x + 40 caracteres hex.</div>';return;}const known=tokenByAddress(addr);if(known){renderTokenResult(known);return;}setBusy($('tokenSearchBtn'),true,'Buscando…');try{const [sym,dec,name]=await Promise.all([view(addr,'symbol',[]),view(addr,'decimals',[]),view(addr,'name',[]).catch?.(()=>null)]);const t={address:addr,symbol:String(sym||'TOKEN'),name:String(name||sym||'Token'),decimals:Number(dec??18),native:false,custom:true};renderTokenResult(t);}catch(e){box.innerHTML=`<div class="error">Contrato não reconhecido como token: ${esc(e.message)}</div>`;}finally{setBusy($('tokenSearchBtn'),false);}}
function renderTokenResult(t){const p=findPair(NATIVE,t),box=$('tokenResult');box.innerHTML=`<div class="card tokenFound"><div><div class="name">${esc(t.symbol)} · ${esc(t.name||'Token')}</div><div class="meta mono">${esc(t.address)}</div><div class="meta">${p?`Pool ASENDEX #${p.poolId}`:'Sem pool ASENDEX encontrada'}</div></div><button class="smallBtn" id="addTokenBtn">${tokenByAddress(t.address)?'Adicionado':'Adicionar'}</button></div>`;const b=$('addTokenBtn');if(b&&!tokenByAddress(t.address))b.onclick=()=>addCustomToken(t);}
function addCustomToken(t){const list=customTokens().filter(x=>String(x.address).toLowerCase()!==t.address.toLowerCase());list.unshift(t);saveCustom(list);tokens.push(t);renderTokenSelectors();refreshBalances();renderTokenResult(t);toast(`${t.symbol} adicionado`);}

async function bootstrap(){try{const b=await bridge('bootstrap');address=b.address||'';bio={available:!!b.biometricAvailable,enabled:!!b.biometricEnabled};$('bioUnlockBtn').style.display=bio.enabled?'block':'none';$('firstRun').style.display=b.hasVault?'none':'block';$('unlockBox').style.display=b.hasVault?'block':'none';if(b.unlocked){await enterApp();}else $('gate').style.display='flex';}catch(e){$('gateError').textContent=e.message;}}
async function importWallet(){const pk=$('privateKey').value,p=$('newPass').value,p2=$('newPass2').value;if(p!==p2)return $('gateError').textContent='As senhas não coincidem';if(cleanHex(pk).length!==64)return $('gateError').textContent='A Private Key Asentum deve ter 32 bytes (64 caracteres hex).';try{$('gateError').textContent='';const r=await bridge('importPrivateKey',{privateKeyHex:pk,password:p});address=r.address;await enterApp();offerBio(p);}catch(e){$('gateError').textContent=e.message;}}
async function createWallet(){const p=$('newPass').value,p2=$('newPass2').value;if(p!==p2)return $('gateError').textContent='As senhas não coincidem';try{const r=await bridge('createWallet',{password:p});address=r.address;await enterApp();offerBio(p);}catch(e){$('gateError').textContent=e.message;}}
async function unlockWallet(){const p=$('unlockPass').value;try{const r=await bridge('unlock',{password:p});address=r.address;await enterApp();}catch(e){$('gateError').textContent=e.message;}}
async function biometricUnlock(){try{$('gateError').textContent='';const r=await bridge('biometricUnlock');address=r.address;await enterApp();}catch(e){$('gateError').textContent=e.message;}}
async function offerBio(password){if(!bio.available||bio.enabled||!password)return;setTimeout(async()=>{if(!confirm('Ativar desbloqueio por biometria/impressão digital neste aparelho?'))return;try{await bridge('enableBiometric',{password});bio.enabled=true;renderSecurity();toast('Biometria ativada');}catch(e){toast('Biometria não ativada: '+e.message)}},500);}
async function enableBioFromSettings(){const p=$('bioPassword').value;if(!p)return toast('Digite sua senha atual');try{await bridge('unlock',{password:p});await bridge('enableBiometric',{password:p});bio.enabled=true;$('bioPassword').value='';renderSecurity();toast('Biometria ativada');}catch(e){toast(e.message)}}
async function disableBio(){try{await bridge('disableBiometric');bio.enabled=false;renderSecurity();toast('Biometria desativada');}catch(e){toast(e.message)}}
function renderSecurity(){$('bioState').textContent=!bio.available?'Não disponível neste aparelho':bio.enabled?'Ativa':'Disponível';$('enableBioBox').style.display=bio.available&&!bio.enabled?'block':'none';$('disableBioBtn').style.display=bio.enabled?'inline-flex':'none';}
async function lockWallet(){await bridge('lock');location.reload();}

async function enterApp(){if(!address){const s=await bridge('state');address=s.address||'';}$('gate').style.display='none';$('app').style.display='block';$('nav').style.display='grid';$('addressShort').textContent=short(address);$('settingsAddress').textContent=address;$('receiveAddress').textContent=address;renderSecurity();await Promise.allSettled([networkCheck(),loadMarkets(),loadActivity(),loadRecents()]);await refreshBalances();setInterval(()=>networkCheck().catch(()=>{}),15000);setInterval(()=>refreshBalances().catch(()=>{}),20000);}

function showTab(id){document.querySelectorAll('.screen').forEach(e=>e.classList.toggle('on',e.id===id));document.querySelectorAll('#nav button').forEach(e=>e.classList.toggle('on',e.dataset.tab===id));if(id==='swap'){networkCheck();quoteSwap();}if(id==='activity')loadActivity();if(id==='browser')loadRecents();window.scrollTo(0,0);}
async function copyAddress(){await bridge('copyAddress');toast('Endereço copiado');}
function receive(){$('receiveOverlay').classList.add('on');}
function closeReceive(){$('receiveOverlay').classList.remove('on');}
function openSend(){$('sendOverlay').classList.add('on');}
function closeSend(){$('sendOverlay').classList.remove('on');$('sendError').textContent='';}
async function sendAse(){const to=$('sendTo').value.trim(),amount=$('sendAmount').value.trim();$('sendError').textContent='';if(!to||!amount)return $('sendError').textContent='Preencha endereço e quantidade';try{const r=await bridge('sendTransfer',{to,amountAse:amount});closeSend();toast('Transferência enviada · '+short(r.txHash));await refreshBalances();await loadActivity();}catch(e){$('sendError').textContent=e.message;}}
function goUrl(){let u=$('url').value.trim();if(!u)return;if(!/^https?:\/\//i.test(u))u='https://'+u;bridge('openBrowser',{url:u}).catch(e=>toast(e.message));}
async function loadRecents(){const b=$('recents');if(!b)return;const r=await bridge('getRecents');b.innerHTML='';if(!r.items?.length)return b.innerHTML='<div class="empty">Nenhum site visitado ainda.</div>';for(const x of r.items){const d=document.createElement('button');d.className='recent';let host=x.url;try{host=new URL(x.url).host}catch{}d.innerHTML=`<span class="favicon">◎</span><span class="grow"><span class="name">${esc(host)}</span><span class="meta">${esc(x.url)}</span></span><span>›</span>`;d.onclick=()=>bridge('openBrowser',{url:x.url});b.appendChild(d);}}
async function clearRecents(){await bridge('clearRecents');loadRecents();}
async function loadActivity(){const r=await bridge('getActivity'),b=$('activityList'),h=$('homeActivity');const html=(r.items||[]).slice(0,50).map(x=>`<div class="activity"><div class="txIcon">↗</div><div class="grow"><div class="name">${esc(x.label||x.method)}</div><div class="meta">${esc(x.origin||'ASENDEX Wallet')}</div></div><div class="right"><div class="good">Enviada</div><div class="meta mono">${esc(short(x.txHash))}</div></div></div>`).join('')||'<div class="empty">Nenhuma transação iniciada pela wallet.</div>';if(b)b.innerHTML=html;if(h)h.innerHTML=(r.items||[]).length?html.split('</div>').slice(0,12).join('</div>'):html;}
function openExplorer(hash){bridge('openBrowser',{url:`${EXPLORER}/tx/${hash}`});}
function maxSwap(){const a=tokenByAddress($('fromToken').value);if(!a)return;let v=balances.get(a.address.toLowerCase())||0n;if(a.native){const usable=v>GAS_RESERVE?v-GAS_RESERVE:0n;v=usable*FEE_DENOM/(FEE_DENOM+FEE_BPS);}$('swapAmount').value=formatUnits(v,a.decimals,12);quoteSwap();}

window.showTab=showTab;window.importWallet=importWallet;window.createWallet=createWallet;window.unlockWallet=unlockWallet;window.biometricUnlock=biometricUnlock;window.enableBioFromSettings=enableBioFromSettings;window.disableBio=disableBio;window.lockWallet=lockWallet;window.copyAddress=copyAddress;window.receive=receive;window.closeReceive=closeReceive;window.openSend=openSend;window.closeSend=closeSend;window.sendAse=sendAse;window.goUrl=goUrl;window.clearRecents=clearRecents;window.swapChanged=swapChanged;window.quoteSwap=quoteSwap;window.executeSwap=executeSwap;window.searchContract=searchContract;window.maxSwap=maxSwap;window.openExplorer=openExplorer;

document.addEventListener('DOMContentLoaded',()=>{['swapAmount','slippage'].forEach(id=>$(id)?.addEventListener(id==='swapAmount'?'input':'change',()=>quoteSwap()));$('fromToken')?.addEventListener('change',()=>swapChanged('from'));$('toToken')?.addEventListener('change',()=>swapChanged('to'));$('flipSwap')?.addEventListener('click',()=>{const a=$('fromToken').value;$('fromToken').value=$('toToken').value;$('toToken').value=a;swapChanged('from');});$('maxSwap')?.addEventListener('click',maxSwap);bootstrap();});